#!/bin/bash
case "$1" in
  purge)
    sudo -u postgres psql -v ON_ERROR_STOP=1 <<EOF
DROP DATABASE IF EXISTS aktin;
DROP USER IF EXISTS aktin;
EOF
    sudo -u postgres psql -v ON_ERROR_STOP=1 <<EOF
DROP DATABASE IF EXISTS i2b2;
DROP USER IF EXISTS i2b2crcdata;
DROP USER IF EXISTS i2b2hive;
DROP USER IF EXISTS i2b2imdata;
DROP USER IF EXISTS i2b2metadata;
DROP USER IF EXISTS i2b2pm;
DROP USER IF EXISTS i2b2workdata;
EOF
;;
esac

